### ISSUE TITLE
Velocity Drift

### ISSUE THREAD

**Issue by ibnufauzanalaula** [xioTechnologies/Gait-Tracking-With-x-IMU#18]
Could you explain how Velocity Drift algorithm work? What is that?

**Comment by xioTechnologies** [comment]
The code will detect when the foot is stationary.  The velocity is calculated during non-stationary periods as the integral of the acceleration measurement.  The drift over the non-stationary period is calculated retrospectively as a linear interpolation between the end of the previous stationary period, where the velocity is known to be zero, and the start of the next stationary period, where the velocity is calculated as a non-zero value due to integral drift.
