### ISSUE TITLE
Filter parameters

### ISSUE THREAD

**Issue by Psomvanshi** [xioTechnologies/Gait-Tracking-With-x-IMU#38]
Hello, Thank you for the code. Clearly, a lot of work has gone into writing and maintaining this code.

My question is about the filter parameters used in this code. How did you determine the parameters needed to filter the data. For instance, in script.m file: 

% HP filter accelerometer data
filtCutOff = 0.001;

How did you determine the filtCutoff to be 0.001? Similarly, how the cutoff for the LP filter was determined to be 5 and also the threshold for stationary period detection was 0.05?

**Comment by xioTechnologies** [comment]
The high-pass filter cut-off frequency was chosen to remove DC content from the accelerometer measurement.  The absolute value is then taken from this and put through the low-pass filter.  The low-pass filter cut-off frequency and threshold were chosen to smooth the values so that the stationary periods would be reliable framed.
